module.exports = app => {
    const router = require("express").Router();

    const bonusManiaCtrl = require("../controllers/bonusManiaCtrl");
    const treasurebowlCtrl = require("../controllers/treasurebowlCtrl");
    const luck88Ctrl = require("../controllers/luck88Ctrl");
    const goldenBullCtrl = require("../controllers/goldenBullCtrl");
    const cocoricoCtrl = require("../controllers/cocoricoCtrl");
    const treasureTigerCtrl = require("../controllers/treasureTigerCtrl");
    const kingOfDragonCtrl = require("../controllers/kingOfDragonCtrl");
    const fortuneGaneshaCtrl = require("../controllers/fortuneGaneshaCtrl");
    const fantasyOktoberfestCtrl = require("../controllers/fantasyOktoberfestCtrl");
    const yummyThanksgivingCtrl = require("../controllers/yummyThanksgivingCtrl");
    const blazingCircusCtrl = require("../controllers/blazingCircusCtrl");
    const edgeOfTheStarsCtrl = require("../controllers/edgeOfTheStarsCtrl");
    const greatestShowCtrl = require("../controllers/greatestShowCtrl");
    const sultansFortuneCtrl = require("../controllers/sultansFortuneCtrl");
    const cinderellasGlassSlipperCtrl = require("../controllers/cinderellasGlassSlipperCtrl");
    const butterflyWildDanceCtrl = require("../controllers/butterflyWildDanceCtrl");
    const yunCaiTongZiCtrl = require("../controllers/yunCaiTongZiCtrl");
    const genghisKhanCtrl = require("../controllers/genghisKhanCtrl");
    const bookOfSkullCtrl = require("../controllers/bookOfSkullCtrl");
    const wuZetianCtrl = require("../controllers/wuZetianCtrl");
    const bombingFruitCtrl = require("../controllers/bombingFruitCtrl");
    const legendOfSwordCtrl = require("../controllers/legendOfSwordCtrl");
    const buzzkillBonanzaCtrl = require("../controllers/buzzkillBonanzaCtrl");
    const aliceInWonderlandCtrl = require("../controllers/aliceInWonderlandCtrl");
    const chivalrousGirlCtrl = require("../controllers/chivalrousGirlCtrl");
    const taoCtrl = require("../controllers/taoCtrl");
    const boxingRooCtrl = require("../controllers/boxingRooCtrl");
    const dimSumCtrl = require("../controllers/dimSumCtrl");
    const dragonsLegendCtrl = require("../controllers/dragonsLegendCtrl");
    const magicalStoreCtrl = require("../controllers/magicalStoreCtrl");
    const wildDetectiveCtrl = require("../controllers/wildDetectiveCtrl");
    const firefightersCtrl = require("../controllers/firefightersCtrl");
    const gypsyCtrl = require("../controllers/gypsyCtrl");
    const jellyManiaCtrl = require("../controllers/jellyManiaCtrl");
    const theGuardOfHadesCtrl = require("../controllers/theGuardOfHadesCtrl");
    const monsterParadeCtrl = require("../controllers/monsterParadeCtrl");
    const dajiCtrl = require("../controllers/dajiCtrl");
    const whiteSnakeLegendCtrl = require("../controllers/whiteSnakeLegendCtrl");
    const monsterFileCtrl = require("../controllers/monsterFileCtrl");
    const wizardryCtrl = require("../controllers/wizardryCtrl");

    router.post("/", bonusManiaCtrl.loadPattern);
    router.post("/treasurebowl", treasurebowlCtrl.loadPattern);
    router.post("/luck88", luck88Ctrl.loadPattern);
    router.post("/goldenbull", goldenBullCtrl.loadPattern);
    router.post("/cocorico", cocoricoCtrl.loadPattern);
    router.post("/treasuretiger", treasureTigerCtrl.loadPattern);
    router.post("/kingofdragon", kingOfDragonCtrl.loadPattern);
    router.post("/fortuneganesha", fortuneGaneshaCtrl.loadPattern);
    router.post("/fantasyoktoberfest", fantasyOktoberfestCtrl.loadPattern);
    router.post("/yummythanksgiving", yummyThanksgivingCtrl.loadPattern);
    router.post("/blazingcircus", blazingCircusCtrl.loadPattern);
    router.post("/edgeofthestars", edgeOfTheStarsCtrl.loadPattern);
    router.post("/greatestshow", greatestShowCtrl.loadPattern);
    router.post("/sultansfortune", sultansFortuneCtrl.loadPattern);
    router.post("/cinderellasglassslipper", cinderellasGlassSlipperCtrl.loadPattern);
    router.post("/butterflywilddance", butterflyWildDanceCtrl.loadPattern);
    router.post("/yuncaitongzi", yunCaiTongZiCtrl.loadPattern);
    router.post("/genghiskhan", genghisKhanCtrl.loadPattern);
    router.post("/bookofskull", bookOfSkullCtrl.loadPattern);
    router.post("/wuzetian", wuZetianCtrl.loadPattern);
    router.post("/bombingfruitwuzetian", bombingFruitCtrl.loadPattern);
    router.post("/legendofsword", legendOfSwordCtrl.loadPattern);
    router.post("/buzzkillbonanza", buzzkillBonanzaCtrl.loadPattern);
    router.post("/aliceinwonderland", aliceInWonderlandCtrl.loadPattern);
    router.post("/chivalrousgirl", chivalrousGirlCtrl.loadPattern);
    router.post("/taoctrlwuzetian", taoCtrl.loadPattern);
    router.post("/boxingroo", boxingRooCtrl.loadPattern);
    router.post("/dimsum", dimSumCtrl.loadPattern);
    router.post("/dragonslegend", dragonsLegendCtrl.loadPattern);
    router.post("/magicalstore", magicalStoreCtrl.loadPattern);
    router.post("/wilddetective", wildDetectiveCtrl.loadPattern);
    router.post("/firefighters", firefightersCtrl.loadPattern);
    router.post("/gypsy", gypsyCtrl.loadPattern);
    router.post("/jellymania", jellyManiaCtrl.loadPattern);
    router.post("/theguardofhades", theGuardOfHadesCtrl.loadPattern);
    router.post("/monsterparade", monsterParadeCtrl.loadPattern);
    router.post("/daji", dajiCtrl.loadPattern);
    router.post("/whitesnakelegend", whiteSnakeLegendCtrl.loadPattern);
    router.post("/monsterfile", monsterFileCtrl.loadPattern);
    router.post("/wizardry", wizardryCtrl.loadPattern);

    app.use('/api', router);
};
